name: ChatChannels
main: com.nisovin.ChatChannels.ChatChannels
version: 1.0
commands:
    channel:
        description: Change channel preferences
        usage: /<command>
        aliases: [ch]
    join:
        description: Join a channel
        usage: /<command> <channel> [pass]
    leave:
        description: Leave a channel
        usage: /<command> <channel>
    yell:
        description: Yell
        usage: /<command> <message>
        aliases: [y]